EdusvKids.WebUI/Controllers/CheckOutController.cs
using HGAPI.DTOs.PurchaseOrderDTOs;
using HGAPI.Models.EN;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Stripe;
using Stripe.Checkout;
using System.Security.Claims;
using static HGAPI.DTOs.PurchaseOrderDTOs.SearchResultPurchaseOrderDTO;
namespace EdusvKids.WebUI.Controllers
{
    public class CheckOutController : Controller
    {
        readonly HttpClient _httpClient;
        public CheckOutController(IHttpClientFactory httpClient)
        {
            _httpClient = httpClient.CreateClient("API");

        }
        public IActionResult Index()
        {
            return View();
        }
        public async Task<IActionResult> OrderConfirmation()
        {
            var service = new SessionService();
            Session session = service.Get(TempData["Session"].ToString());


            if (session.PaymentStatus == "paid")
            {
                var transaction = session.PaymentIntentId.ToString();
                var response = await _httpClient.PutAsJsonAsync("/order", new { NumOrder= TempData["NumOrder"].ToString() });
                if (response.IsSuccessStatusCode)
                {
                    return View("Succes");
                }                   
            }
            return View("Login");
        }

        public IActionResult Succes()
        {
            return View();
        }
        public IActionResult Login()
        {
            return View();
        }
        public IActionResult Error()
        {
            return View();
        }
        public async Task<IActionResult> CheckOut2( string productName, decimal price, int total, int Id)
        {

            int amount = (int)total / (int)price;

            DateTime now = DateTime.Now;
            var claimsPrincipal = User as ClaimsPrincipal;
            int idUser = 0;
            int.TryParse(claimsPrincipal.FindFirst(ClaimTypes.NameIdentifier)?.Value, out idUser);
            string numOrder = Guid.NewGuid().ToString();
            CreatePurchaseOrderDTO purchaseOrderDTO = new CreatePurchaseOrderDTO
            {
                IdProductGames = Id,
                IdUserPlayer = idUser,
                NameOrder = numOrder,
                DateOrder=DateTime.Now,
                Headline=productName,
                Total = total
            };
            var response = await _httpClient.PostAsJsonAsync("/order", purchaseOrderDTO);
            if (response.IsSuccessStatusCode)
            {
                var domain = "https://paymentgateway.somee.com/";

                var options = new SessionCreateOptions
                {
                    SuccessUrl = domain + $"CheckOut/OrderConfirmation/",
                    CancelUrl = domain + "CheckOut/Login",
                    LineItems = new List<SessionLineItemOptions>(),
                    Mode = "payment"
                };

                var sessionListItem = new SessionLineItemOptions
                {
                    PriceData = new SessionLineItemPriceDataOptions
                    {
                        Currency = "usd",
                        UnitAmount = (long)(price * 100),
                        ProductData = new SessionLineItemPriceDataProductDataOptions
                        {
                            Name = productName.ToString(),
                        }
                    },
                    Quantity = amount
                };

                options.LineItems.Add(sessionListItem);


                var service = new SessionService();
                Session session = service.Create(options);

                TempData["Session"] = session.Id;
                TempData["NumOrder"] = numOrder;

                Response.Headers.Add("Location", session.Url);
                return new StatusCodeResult(303);
            }      
            else
                return View("Error");

        }
        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Pay(string productName, int total, int Id)
        {
           
            DateTime now = DateTime.Now;
            var claimsPrincipal = User as ClaimsPrincipal;
            int idUser = 0;
            int.TryParse(claimsPrincipal.FindFirst(ClaimTypes.NameIdentifier)?.Value, out idUser);
            string numOrder = Guid.NewGuid().ToString();
            CreatePurchaseOrderDTO purchaseOrderDTO = new CreatePurchaseOrderDTO
            {
                IdProductGames = Id,
                IdUserPlayer = idUser,
                NameOrder = numOrder,
                DateOrder = DateTime.Now,
                Headline = productName,
                Total = total
            };
            var response = await _httpClient.PostAsJsonAsync("/order", purchaseOrderDTO);
            if (response.IsSuccessStatusCode)
            {
                return Json(new { result = 1 });
            }
            else
                return Json(new { result = 0 });

        }
    }
}

EdusvKids.WebUI/Controllers/HomeController.cs
using EdusvKids.WebUI.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace EdusvKids.WebUI.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Productos()
        {
            return View();
        }

        public IActionResult Monedas()
        {
            return View();
        }
        public IActionResult Descargar()
        {
            return View();
        }

        public IActionResult Pagar()
        {
            return View();
        }

        public IActionResult Cuenta()
        {
            return View();
        }

        public IActionResult Crear()
        {
            return View();
        }

        [Authorize]
        public IActionResult Vida()
        {
            return View();
        }

        public IActionResult Inicio()
        {
            return View();
        }


        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View();
        }
    }
}

EdusvKids.WebUI/Views/Home/Crear.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Crear Cuenta</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,700" rel="stylesheet">
    <link rel="stylesheet" href="~/css/Cuenta.css">

</head>
<body>

    <body class="align">

        <div class="grid">

            <form action="https://httpbin.org/post" method="POST" class="form login">

                <div class="form__field">
                    <label for="login__Nombre">
                        <svg class="icon">
                            <use xlink:href="#icon-email"></use>
                        </svg><span class="hidden">Nombre</span>
                    </label>
                    <input autocomplete="Nombre" id="login__nombre" type="text" name="Nombre" class="form__input" placeholder="Nombre" required>
                </div>

                <div class="form__field">
                    <label for="login__username">
                        <svg class="icon">
                            <use xlink:href="#icon-user"></use>
                        </svg><span class="hidden">Nombre</span>
                    </label>
                    <input autocomplete="username" id="login__username" type="text" name="username" class="form__input" placeholder="Gmail" required>
                </div>


                <div class="form__field">
                    <label for="login__password">
                        <svg class="icon">
                            <use xlink:href="#icon-lock"></use>
                        </svg><span class="hidden">Contraseña</span>
                    </label>
                    <input id="login__password" type="password" name="password" class="form__input" placeholder="Password" required>
                </div>

                <div class="form__field">
                    <button type="button" class="btn btn-danger">Crear Cuenta
                    </button>
                </div>

            </form>



        </div>

        <svg xmlns="http://www.w3.org/2000/svg" class="icons">
            <symbol id="icon-arrow-right" viewBox="0 0 1792 1792">
                <path d="M1600 960q0 54-37 91l-651 651q-39 37-91 37-51 0-90-37l-75-75q-38-38-38-91t38-91l293-293H245q-52 0-84.5-37.5T128 1024V896q0-53 32.5-90.5T245 768h704L656 474q-38-36-38-90t38-90l75-75q38-38 90-38 53 0 91 38l651 651q37 35 37 90z" />
            </symbol>
            <symbol id="icon-lock" viewBox="0 0 1792 1792">
                <path d="M640 768h512V576q0-106-75-181t-181-75-181 75-75 181v192zm832 96v576q0 40-28 68t-68 28H416q-40 0-68-28t-28-68V864q0-40 28-68t68-28h32V576q0-184 132-316t316-132 316 132 132 316v192h32q40 0 68 28t28 68z" />
            </symbol>
            <symbol id="icon-user" viewBox="0 0 1792 1792">
                <path d="M1600 1405q0 120-73 189.5t-194 69.5H459q-121 0-194-69.5T192 1405q0-53 3.5-103.5t14-109T236 1084t43-97.5 62-81 85.5-53.5T538 832q9 0 42 21.5t74.5 48 108 48T896 971t133.5-21.5 108-48 74.5-48 42-21.5q61 0 111.5 20t85.5 53.5 62 81 43 97.5 26.5 108.5 14 109 3.5 103.5zm-320-893q0 159-112.5 271.5T896 896 624.5 783.5 512 512t112.5-271.5T896 128t271.5 112.5T1280 512z" />
            </symbol>
        </svg>

    </body>

</body>
</html>

EdusvKids.WebUI/Views/Home/Cuenta.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Cuenta</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,700" rel="stylesheet">
    <link rel="stylesheet" href="~/css/Cuenta.css">

</head>
<body>
    <body class="align">

        <div class="grid">

            <form action="https://httpbin.org/post" method="POST" class="form login">

                <div class="form__field">
                    <label for="login__username">
                        <svg class="icon">
                            <use xlink:href="#icon-user"></use>
                        </svg><span class="hidden">Nombre</span>
                    </label>
                    <input autocomplete="username" id="login__username" type="text" name="username" class="form__input" placeholder="Username" required>
                </div>

                <div class="form__field">
                    <label for="login__password">
                        <svg class="icon">
                            <use xlink:href="#icon-lock"></use>
                        </svg><span class="hidden">Contraseña</span>
                    </label>
                    <input id="login__password" type="password" name="password" class="form__input" placeholder="Password" required>
                </div>

                <div class="form__field">
                    <button type="button" class="btn btn-danger">Iniciar sesion</button>
                </div>

            </form>

            <p class="text--center">
                <a asp-controller="Home" asp-action="Crear">Crear Cuenta</a>

                
                <svg class="icon">
                    <use xlink:href="#icon-arrow-right"></use>
                </svg>
            </p>

        </div>

        <svg xmlns="http://www.w3.org/2000/svg" class="icons">
            <symbol id="icon-arrow-right" viewBox="0 0 1792 1792">
                <path d="M1600 960q0 54-37 91l-651 651q-39 37-91 37-51 0-90-37l-75-75q-38-38-38-91t38-91l293-293H245q-52 0-84.5-37.5T128 1024V896q0-53 32.5-90.5T245 768h704L656 474q-38-36-38-90t38-90l75-75q38-38 90-38 53 0 91 38l651 651q37 35 37 90z" />
            </symbol>
            <symbol id="icon-lock" viewBox="0 0 1792 1792">
                <path d="M640 768h512V576q0-106-75-181t-181-75-181 75-75 181v192zm832 96v576q0 40-28 68t-68 28H416q-40 0-68-28t-28-68V864q0-40 28-68t68-28h32V576q0-184 132-316t316-132 316 132 132 316v192h32q40 0 68 28t28 68z" />
            </symbol>
            <symbol id="icon-user" viewBox="0 0 1792 1792">
                <path d="M1600 1405q0 120-73 189.5t-194 69.5H459q-121 0-194-69.5T192 1405q0-53 3.5-103.5t14-109T236 1084t43-97.5 62-81 85.5-53.5T538 832q9 0 42 21.5t74.5 48 108 48T896 971t133.5-21.5 108-48 74.5-48 42-21.5q61 0 111.5 20t85.5 53.5 62 81 43 97.5 26.5 108.5 14 109 3.5 103.5zm-320-893q0 159-112.5 271.5T896 896 624.5 783.5 512 512t112.5-271.5T896 128t271.5 112.5T1280 512z" />
            </symbol>
        </svg>

    </body>

</body>
</html>

EdusvKids.WebUI/Views/Home/Descargar.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Descarga</title>
	<link rel="stylesheet" href="~/css/Descargar.css">

</head>

<body>


	<header>
		<div class="banner"></div>
		<nav>

			<div id="logo">



				The <br> Warrior
			</div>
			<ul class="navigation-menu">
				<li>

					<a asp-controller="Home" asp-action="Productos">Tienda</a>
				<li>
					<a asp-controller="Home" asp-action="Descargar">Descargar</a>


				</li>
				<li>
					<a asp-controller="Home" asp-action="Cuenta">Cuenta</a>

				</li>

			</ul>

		</nav>
	</header>


	<div class="dashboard">

		<div class="data">
			<div class="schedule-table neo-box">
				<div class="subtitle">
					<h2></h2>
				</div>
				<table>
					<img src="~/images/linux.png" alt="50">
				</table>

				<button>Descargar para Linux</button>
			</div>

			<div class="exercise-table neo-box">
				<div class="subtitle">
					<h2></h2>
				</div>
				<table>
					<img src="~/images/android.jpg">
				</table>
				<button>
					<a href="https://play.google.com/store/apps/details?id=org.godotengine.gamehappy&amp;pli=1" type="button">
						Descargar para Android
					</a>
				</button>
				
				
			</div>

			<div class="exercise-table neo-box">
				<div class="subtitle">
					<h2></h2>
				</div>
				<table>
					<img src="~/images/Microsoft .jpg">
				</table>
				<button>Descargar para Windows </button>
			</div>


			<div class="activity-feed">
				<p class="marquee"><span><span> Descarga nuestra app en tu dispositivo favorito!!!</span></span></p>
			</div>
		</div>

</body>
</html>

EdusvKids.WebUI/Views/Home/Index.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Pagina</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/meyer-reset/2.0/reset.min.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,400;0,500;0,600;0,700;0,800;1,400;1,500;1,600;1,700;1,800&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/meyer-reset/2.0/reset.min.css">
    <link rel="stylesheet" href="~/css/Index.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/prefixfree/1.0.7/prefixfree.min.js"></script>

</head>
<body>
    <header>
        <div class="banner"></div>
        <nav>

            <div id="logo">



                The <br> Warrior
            </div>
            <ul class="navigation-menu">
                <li>
                    
                    <a asp-controller="Home" asp-action="Productos">Tienda</a>
                <li>
                    <a asp-controller="Home" asp-action="Descargar">Descargar</a>


                </li>
                <li>
                    <a asp-controller="Account" asp-action="SignIn">Cuenta</a>

                </li>

            </ul>

        </nav>
    </header>
    <section class="hero">
        <h1>
            Explora mundos fantásticos, descubre secretos y tesoros
        </h1>


    </section>


    <section>
        <h2>¡Descubre más!</h2>

        <ul class="services">
            <li class="card-large card-dark card-wide" id="serv-groom">
                <div class="card-image"><img src="~/images/juego.jpg"></div>
                <ul>
                    Compra Monedas
                    <span class="subtitle">La victoria tiene un precio, ¡pero con nuestras monedas, la gloria está garantizada!</span>
                    <li><a href="#">Bolsa de Monedas</a><span>1,200 monedas</span></li>
                    <li>
                        <a href="#"> Saco de monedas</a><span>
                            2,500 monedas
                        </span>
                    </li>
                    <li><a href="#"> Puñado de monedas</a><span>80 monedas</span></li>


                </ul>


            </li>
            <li class="card-large card-dark card-wide" id="serv-board">
                <div class="card-image"><img src="~/images/juego2.jpg"></div>
                <ul>


                    Pixel perfecto, diversión sin fin. ¡Experimenta la era dorada de los videojuegos en cada nivel!


                </ul>

            </li>
        </ul>
    </section>

    <section id="locate">

        <div>
            <h2>The  Warrior</h2>
            <p>"Desafía los límites, vive la fantasía: tu épica aventura te espera frente a la pantalla."</p>

            <button class="btn-outline-dark btn-hover-color">
                <span class="material-symbols-outlined">
                    games
                </span> Jugar
            </button>
        </div>
        </div>
    </section>




</body>
</html>

EdusvKids.WebUI/Views/Home/Inicio.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Comenzar</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">

	<link href="https://fonts.googleapis.com/css?family=Barlow+Condensed:500,800" rel="stylesheet">
	<link rel="stylesheet" href="css/Inicio.css">

</head>
<body>
	<div class="wrapper run-animation" id="animate">
		<div class="logo">

			<span class="marvel">THE</span>
			<span class="studios">WARRIOR </span>

			<div>
			 <a asp-controller="Home" asp-action="Index" class="restart">Comenzar</a>
			</div>
		</div>
	</div>

	<div class="images"></div>
	<script src="~/js/Inicio.js"></script>

</body>
</html>

EdusvKids.WebUI/Views/Home/Monedas.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Monedas</title>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans+Condensed:300,700' rel='stylesheet' type='text/css'>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="~/css/Monedas.css">

</head>
<body>

    <header>
        <div class="banner"></div>
        <nav>

            <div id="logo">



                The <br> Warrior
            </div>
            <ul class="navigation-menu">
                <li>

                    <a asp-controller="Home" asp-action="Productos">Tienda</a>
                <li>
                    <a asp-controller="Home" asp-action="Descargar">Descargar</a>


                </li>
                <li>
                    <a asp-controller="Home" asp-action="Cuenta">Cuenta</a>

                </li>

            </ul>

        </nav>
    </header>
    <div class='row'>
        <div class='product--blue'>
            <div class='product_inner'>
                <img src='~/images/monedas.png' width='300'>
                <p>Pila de monedas</p>
                <p>
                    550
                    monedas
                </p>
                <p>Precio $4,99</p>
                <button> 
                <a href="https://buy.stripe.com/test_7sIbMqfgMciw86c5kq">
                    Comprar
                </a>
                </button>
            </div>

        </div>
        <div class='product--orange'>
            <div class='product_inner'>
                <img src='~/images/monedas.png' width='300'>
                <p>Puñado de monedas</p>
                <p>
                    80
                    monedas
                </p>
                <p>Precio $0.99 </p>
                <button>
                    <a href="https://buy.stripe.com/test_7sIbMqfgMciw86c5kq">
                        Comprar
                    </a>
                </button>
            </div>
        </div>
        <div class='product--red'>
            <div class='product_inner'>
                <img src='~/images/monedas.png' width='300'>
                <p>Saco de monedas</p>
                <p>
                    2,500
                    monedas
                </p>
                <p>Precio $19,99</p>
                <button>
                <a href="https://buy.stripe.com/test_7sIbMqfgMciw86c5kq">
                    Comprar
                </a>
                </button>
            </div>

        </div>
        <div class='product--green'>
            <div class='product_inner'>
                <img src='~/images/monedas.png' width='300'>
                <p>Caja de monedas</p>
                <p>
                    6,500
                    monedas
                </p>
                <p>Precio $49,99</p>
                <button>
                    <a href="https://buy.stripe.com/test_7sIbMqfgMciw86c5kq">
                        Comprar
                    </a>
                </button>
            </div>

        </div>
        <div class='product--yellow'>
            <div class='product_inner'>
                <img src='~/images/monedas.png' width='300'>
                <p>Cofre de monedas</p>
                <p>
                    14,000
                    monedas
                </p>
                <p>Precio $99,99</p>
                <button>
                    <a href="https://buy.stripe.com/test_7sIbMqfgMciw86c5kq">
                        Comprar
                    </a>
                </button>
            </div>

        </div>
        <div class='product--pink'>
            <div class='product_inner'>
                <img src='~/images/monedas.png' width='300'>
                <p>Bolsa de Monedas</p>
                <p>
                    1,200
                    monedas
                </p>
                <p>Precio $9.99 </p>
                <button>
                    <a href="https://buy.stripe.com/test_7sIbMqfgMciw86c5kq">
                        Comprar
                    </a>
                </button>
            </div>

        </div>
    </div>
    <script src='//cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>
    <script src='//cdnjs.cloudflare.com/ajax/libs/angular.js/1.3.14/angular.min.js'></script>
    <script src="~/js/Monedas.js"></script>

</body>
</html>

EdusvKids.WebUI/Views/Home/Productos.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Productos</title>
    <link rel="stylesheet" href="~/css/Productos.css">

</head>
    <body>
        <div class="container">
            <header>
                <div class="banner"></div>
                <nav>

                    <div id="logo">



                        The <br> Warrior
                    </div>
                    <ul class="navigation-menu">
                        <li>

                            <a asp-controller="Home" asp-action="Productos">Tienda</a>
                        <li>
                            <a asp-controller="Home" asp-action="Descargar">Descargar</a>


                        </li>
                        <li>
                            <a asp-controller="Home" asp-action="Cuenta">Cuenta</a>

                        </li>

                    </ul>

                </nav>
            </header>

            <main>

                <section class="content">
                    <div class="item-nav">
                    </div>
                    <section class="products">
                        <article class="item-card">
                            <div class="item-intro">
                                <div class="price-special">
                                </div>
                            </div>
                            <div class="image-wrapper" id="item-img-1">
                            </div>
                            <div class="content-wrapper" id="item-desc-1">
                                <div class="item-basic-info">
                                </div>
                                <div class="item-more-info">

                                    <button type="button">
                                    <a asp-controller="Home" asp-action="Vida">Aumento de Vidas</a>
                                </button>
                                </div>
                            </div>
                        </article>

                        <article class="item-card">
                            <div class="item-intro">
                                <div class="price-special">
                                </div>
                            </div>
                            <div class="image-wrapper" id="item-img-2">
                            </div>
                            <div class="content-wrapper" id="item-desc-2">
                                <div class="item-basic-info">
                                </div>
                                <div class="item-more-info">

                                    <button type="button">
                                  
                                    <a asp-controller="Home" asp-action="Monedas">Aumento en bonificación en cofres</a>
                                </button>
                                </div>
                            </div>
                        </article>


                    </section>
                </section>
            </main>
            <footer>
                <p class="tagline"> ©The Warrior-2023</p>
            </footer>
        </div>
    </body>
</html>

EdusvKids.WebUI/Views/Home/Vida.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Vidas</title>
    <link rel='stylesheet' href='https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css'>
    <link rel="stylesheet" href="~/css/Vida.css">

</head>
<body>
    <nav class="flex-nav">
        <div class="container">
            <div class="grid menu">
                <div class="column-xs-8 column-md-6">
                    <p id="highlight">The Warrior</p>
                </div>
                <div class="column-xs-4 column-md-6">
                    <a href="#" class="toggle-nav">Menu <i class="ion-navicon-round"></i></a>
                    <ul>
                        <li class="nav-item">
                            <a asp-controller="Home" asp-action="Productos">Tienda</a>
                        </li>
                        <li class="nav-item">
                            <a asp-controller="Home" asp-action="Descargar">Descargar</a>
                        </li>
                        <li class="nav-item">
                            <a asp-controller="Home" asp-action="Cuenta">Cuenta</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </nav>
    <main>
        <div class="container">

            <div class="grid product">
                <div class="column-xs-12 column-md-7">
                    <div class="product-gallery">
                        <div class="product-image">
                            <img class="active" src="https://i.pinimg.com/564x/e8/99/be/e899be4ee27d08f84dee393ff39e8913.jpg">
                        </div>
                        <ul class="image-list">
                            <li class="image-item"><img src="https://i.pinimg.com/564x/b7/08/5d/b7085d0a3c70020b9b30736349a3e8ae.jpg"></li>
                            <li class="image-item"><img src="https://i.pinimg.com/564x/27/20/48/2720488c28fe5e140b18fa53783bab81.jpg"></li>
                            <li class="image-item"><img src="https://i.pinimg.com/564x/e1/17/de/e117de933783fa48980b0ae76ec9a537.jpg"></li>
                        </ul>
                    </div>
                </div>
                <div class="column-xs-12 column-md-5">
                    <h1>
                        Aumentos de vida
                    </h1>
                    <h2>
                        2.00 US$
                    </h2>
                    <div class="description">
                        <p>Aumentar la vida maxima del player permanentemente de 100 a 200</p>
                    </div>

                    <button type="button" id="btnPay" class="add-to-cart">
                        Comprar                       
                    </button>
                   @*  <button class="add-to-cart">
                        <a href="https://buy.stripe.com/test_fZe2bQ7Okaao7289AH">
                            Comprar
                        </a>
                    </button> *@
                </div>
            </div>

        </div>
    </main>
    <footer>
        <div class="grid">
            <div class="column-xs-12">
                <p class="copyright">&copy; The Warrior
            </div>
        </div>
    </footer>
    <script src="~/js/Vida.js"></script>   
    <script src="~/lib/jquery/dist/jquery.min.js"></script>  
    <script>
        $(function () { 
            $("#btnPay").click(function () {             
                $.ajax({
                    url: '@Url.Action("Pay", "CheckOut")',
                    data: { productName: 'Aumento de vida 200', total: 2, Id: 100 },
                    type:'Post',
                    success: function (objResult) {
                         if (objResult && objResult.result && objResult.result== 1){
                            document.location = 'https://buy.stripe.com/test_fZe2bQ7Okaao7289AH';
                         }
                         else {
                             alert("Sucedio un error al enviar el pago");
                         }
                   }
              });
            });
        })
    </script>
</body>
</html>